<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.30" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenLearning.Assignments\OpenLearning.Assignments.csproj" />
    <ProjectReference Include="..\OpenLearning.Auth\OpenLearning.Auth.csproj" />
    <ProjectReference Include="..\OpenLearning.CourseManagement\OpenLearning.CourseManagement.csproj" />
    <ProjectReference Include="..\OpenLearning.Enrollment\OpenLearning.Enrollment.csproj" />
  </ItemGroup>
</Project>
