<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="WebPush" Version="1.0.13" />
    <ProjectReference Include="..\OpenLearning.Auth\OpenLearning.Auth.csproj" />
    <ProjectReference Include="..\OpenLearning.CourseManagement\OpenLearning.CourseManagement.csproj" />
    <ProjectReference Include="..\OpenLearning.Enrollment\OpenLearning.Enrollment.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.30" />
  </ItemGroup>

</Project>
