<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\OpenLearning.Auth\OpenLearning.Auth.csproj" />
    <ProjectReference Include="..\OpenLearning.CourseManagement\OpenLearning.CourseManagement.csproj" />
    <ProjectReference Include="..\OpenLearning.Enrollment\OpenLearning.Enrollment.csproj" />
    <ProjectReference Include="..\OpenLearning.Progress\OpenLearning.Progress.csproj" />
    <ProjectReference Include="..\OpenLearning.UserManagement\OpenLearning.UserManagement.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenLearning.Assessments\OpenLearning.Assessments.csproj" />
    <ProjectReference Include="..\OpenLearning.Ecommerce\OpenLearning.Ecommerce.csproj" />
    <ProjectReference Include="..\OpenLearning.Scorm\OpenLearning.Scorm.csproj" />
    <ProjectReference Include="..\OpenLearning.Chat\OpenLearning.Chat.csproj" />
  </ItemGroup>

</Project>
