<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\OpenLearning.Auth\OpenLearning.Auth.csproj" />
    <ProjectReference Include="..\OpenLearning.CourseManagement\OpenLearning.CourseManagement.csproj" />
    <ProjectReference Include="..\OpenLearning.Enrollment\OpenLearning.Enrollment.csproj" />
    <ProjectReference Include="..\OpenLearning.Progress\OpenLearning.Progress.csproj" />
    <ProjectReference Include="..\OpenLearning.UserManagement\OpenLearning.UserManagement.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.30">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenLearning.Assessments\OpenLearning.Assessments.csproj" />
    <ProjectReference Include="..\OpenLearning.Classes\OpenLearning.Classes.csproj" />
    <ProjectReference Include="..\OpenLearning.Ecommerce\OpenLearning.Ecommerce.csproj" />
    <ProjectReference Include="..\OpenLearning.Exams\OpenLearning.Exams.csproj" />
    <ProjectReference Include="..\OpenLearning.Scorm\OpenLearning.Scorm.csproj" />
    <ProjectReference Include="..\OpenLearning.Chat\OpenLearning.Chat.csproj" />
    <ProjectReference Include="..\OpenLearning.Community\OpenLearning.Community.csproj" />
    <ProjectReference Include="..\OpenLearning.Ratings\OpenLearning.Ratings.csproj" />
    <ProjectReference Include="..\OpenLearning.Certificates\OpenLearning.Certificates.csproj" />
    <ProjectReference Include="..\OpenLearning.Notifications\OpenLearning.Notifications.csproj" />
    <ProjectReference Include="..\OpenLearning.Storage\OpenLearning.Storage.csproj" />
    <ProjectReference Include="..\OpenLearning.Logging\OpenLearning.Logging.csproj" />
    <ProjectReference Include="..\OpenLearning.SystemConfig\OpenLearning.SystemConfig.csproj" />
    <ProjectReference Include="..\OpenLearning.Memberships\OpenLearning.Memberships.csproj" />
    <ProjectReference Include="..\OpenLearning.Operations\OpenLearning.Operations.csproj" />
    <ProjectReference Include="..\OpenLearning.Assignments\OpenLearning.Assignments.csproj" />
    <ProjectReference Include="..\OpenLearning.StudyTools\OpenLearning.StudyTools.csproj" />
    <ProjectReference Include="..\OpenLearning.Settlement\OpenLearning.Settlement.csproj" />
  </ItemGroup>

</Project>
